/*
 * Smart Lab RA API
 *
 * Documento OAS para la API Smart Lab RA
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CodigoQr : IEquatable<CodigoQr>
    { 
        /// <summary>
        /// Nombre del laboratorista
        /// </summary>
        /// <value>Nombre del laboratorista</value>

        [DataMember(Name="nombre_usuario")]
        public string nombre_usuario { get; set; }

        /// <summary>
        /// Sucursal del laboratorio
        /// </summary>
        /// <value>Sucursal del laboratorio</value>

        [DataMember(Name="nombre_tenant")]
        public string Nombre_tenant { get; set; }

        /// <summary>
        /// Subdominio al cual tiene que apuntar la API
        /// </summary>
        /// <value>Subdominio al cual tiene que apuntar la API</value>

        [DataMember(Name="subdominio")]
        public string Subdominio { get; set; }

        /// <summary>
        /// Token para la autorización del laboratorista
        /// </summary>
        /// <value>Token para la autorización del laboratorista</value>

        [DataMember(Name="api_token")]
        public string Api_token { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CodigoQr {\n");
            sb.Append("  NombreLaboratorista: ").Append(nombre_usuario).Append("\n");
            sb.Append("  Sucursal: ").Append(Nombre_tenant).Append("\n");
            sb.Append("  Subdominio: ").Append(Subdominio).Append("\n");
            sb.Append("  Token: ").Append(Api_token).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CodigoQr)obj);
        }

        /// <summary>
        /// Returns true if CodigoQr instances are equal
        /// </summary>
        /// <param name="other">Instance of CodigoQr to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CodigoQr other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    nombre_usuario == other.nombre_usuario ||
                    nombre_usuario != null &&
                    nombre_usuario.Equals(other.nombre_usuario)
                ) && 
                (
                    Nombre_tenant == other.Nombre_tenant ||
                    Nombre_tenant != null &&
                    Nombre_tenant.Equals(other.Nombre_tenant)
                ) && 
                (
                    Subdominio == other.Subdominio ||
                    Subdominio != null &&
                    Subdominio.Equals(other.Subdominio)
                ) && 
                (
                    Api_token == other.Api_token ||
                    Api_token != null &&
                    Api_token.Equals(other.Api_token)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (nombre_usuario != null)
                    hashCode = hashCode * 59 + nombre_usuario.GetHashCode();
                    if (Nombre_tenant != null)
                    hashCode = hashCode * 59 + Nombre_tenant.GetHashCode();
                    if (Subdominio != null)
                    hashCode = hashCode * 59 + Subdominio.GetHashCode();
                    if (Api_token != null)
                    hashCode = hashCode * 59 + Api_token.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CodigoQr left, CodigoQr right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CodigoQr left, CodigoQr right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
